### ISSUE TITLE
Cache Structure more efficiently

### ISSUE THREAD

**Issue by danrot** [sulu-cmf/sulu#117]
The structures should be cached in a more efficient way. The constructor should not call methods which loop over all tags and so on. Have a look at the mechanism in the Webspace Component, where only keys instead of entire objects are serialized, and put together afterwards.

**Comment by dantleech** [comment]
Should we close this in favor of? https://github.com/sulu-cmf/sulu/issues/685 @danrot

**Comment by danrot** [comment]
I would say it is linked now anyway, so we can close it at the very end. Could be seen as a reminder, not that we make the same mistake again.

**Comment by dantleech** [comment]
It will still be referenced in the issue if we close it. I think we need to get the list of issues down -- if we aggregate issues in other issues thats ok imo.

**Comment by danrot** [comment]
I am not really for aggregating issues, because you can't close them partly. Maybe it is a bit different for the content, because it is quite a big refactoring. So we'll close this one now, but this should not get a habit imo.
