### ISSUE TITLE
Allow meta title for Template Content Type Parameters and add Content Type Values

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#307]
e.g.

``` xml
<property name="select" type="select">
    <meta>
        <title lang="de">Select</title>
        <title lang="en">Select</title>
     </meta>
     <params>
         <param name="option" value="1">
             <meta>
                 <title lang="de">Herr</title>
                 <title lang="en">Mr</title>
             </meta>
         </param>
         <param name="option" value="2">
             <meta>
                 <title lang="de">Frau</title>
                 <title lang="en">Mrs</title>
             </meta>
         </param>
    </params>
</property>

```

**Comment by danrot** [comment]
@alexander-schranz I am soooo sorry, we just decided that we don't want to have these values-tags, because we have to add this meta values to the params anyway for the smartcontent... I hope you don't lose too much work because of this.

**Comment by alexander-schranz** [comment]
so @chirimoya dont wanted to split between options and data.
I thought that the smartcontent values (displayTypes) would also be values and not an option for the smartcontent type.

**Comment by danrot** [comment]
We also thought about that, but it's also not a clean solution, because you have to allow multiple `<values>`-tags then, as soon as a second option appears. And if we implement this it's too similar too the params, and the double amount of code to maintain for practically no use.

**Comment by alexander-schranz** [comment]
ok :)

**Comment by wachterjohannes** [comment]
@danrot @chirimoya what did you think is this a good idea?

i would create a third type of param `translateable` or something similar ... we could leave the others as it is because they are from type `string` or `collection`. I would not have to refactor anything!

```xml
<property name="smart_content" type="smart_content">
    <meta>
        <title lang="de">Smart Content Auswahl</title>
    </meta>

    <params>
        <param name="max_per_page" value="5"/>
        <param name="properties" type="collection">
            <param name="title" value="title"/>
        </param>
        <param name="display_as" type="collection">
            <param name="two" type="translatable">
                <meta>
                    <title lang="de">Zwei Spalten</title>
                    <title lang="en">Two columns</title>

                    <info_text lang="de">Die Seiten werden in zwei Spalten dargestellt</info_text>
                    <info_text lang="en">The pages would be displayed in two columns</info_text>
                </meta>
            </param>
        </param>
    </params>
</property>
```

**Comment by wachterjohannes** [comment]
also i could add the type `boolean` to validate values!

**Comment by danrot** [comment]
Hm, then you couple the structure of the param to the value in type... In an ideal world I would prefer it without the type.

But if I see it correctly we have already done that in the collection type, why do we need it there?

**Comment by wachterjohannes** [comment]
more or less because of http://symfony.com/doc/current/components/dependency_injection/parameters.html#array-parameters symfony parameter.

they use this type to! addionally made this the implementation very easy!

**Comment by wachterjohannes** [comment]
symfony use the types:
* collection
* string
* constant

**Comment by alexander-schranz** [comment]
the collection type is needed e.g.
```
languages:
    en
show:
    false
```

would result without a collection type 
``` json
{
    languages: en,
    show: false,
}
```
with collection type on languages
``` json
{
    languages: [
        en
    ],
    show: false,
}
```

**Comment by wachterjohannes** [comment]
@alexander-schranz i dont understand your comment (=

**Comment by alexander-schranz** [comment]
@wachterjohannes example why collection type is important languages will be everytime an array also when it only have one child.

**Comment by wachterjohannes** [comment]
could be done without the type because of the xml structure.

**Comment by alexander-schranz** [comment]
If you handle every param as collection its ok else you will get problems with dynamic params which should arrays and you get only one. Was also a Problem in the Zend1 Config parser.

**Comment by danrot** [comment]
Your example is just written wrong, assuming you wanted to use yaml:
```yaml
languages:
    - en
show: false
```

Same is valid for xml files, there you just have something like this:
```xml
<param name="max_per_page" value="5"/>
<param name="properties">
    <param name="title" value="title"/>
</param>
```
Here it is also clear that the second value is a collection, whereby the first is not.

However being compatible to symfony seems fine to me. So I am also fine with the translatable solution, if it makes things really easier.

But how are the values passed to the template? All of them? Only the used translation? Where is decided which translation will be used?

**Comment by wachterjohannes** [comment]
@danrot the only problem is when you have an empty array thats not easy to check!

**Comment by wachterjohannes** [comment]
we also need a type `service` which provides params for example checkbox content type. therefore we should leave this `type` xml parameter
