### ISSUE TITLE
[ContactBundle] (#121) Provide service to get countries

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#385]
<a href="https://github.com/dantleech"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/530801?v=2" /></a>
By @dantleech *from* https://github.com/sulu-cmf/SuluContactBundle/issues/121

Add a country provider `sulu.contact.provider.country` which can provide countries.

**Comment by danrot** [comment]
Closed in favour of #758
