### ISSUE TITLE
[ContactBundle] (#103) Missing class var declaration

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#387]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluContactBundle/issues/103

see https://scrutinizer-ci.com/g/sulu-cmf/SuluContactBundle/inspections/a20dda10-568e-44d6-ba20-b6a955ebe206/issues/files/Controller/AbstractContactController.php?status=new&orderField=path&order=asc#inspectioncomment-104613666

**Comment by danrot** [comment]
I guess we should do a cleanup some day anyway, but if scrutinizer is the source we could use this instead, and don't have to add separate tickets for it. And the link doesn't work anymore.

Summary: I close this issue :-)
