### ISSUE TITLE
[ContactBundle] Make additional information sortable (Email, Phone, Address, ...)

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#400]
<a href="https://github.com/chirimoya"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/627313?v=2" /></a>
By @chirimoya *from* https://github.com/sulu-cmf/SuluContactBundle/issues/3

**Comment by danrot** [comment]
@chirimoya Can this be closed? Looks to me like the list is sortable by email:
![image](https://cloud.githubusercontent.com/assets/405874/6199037/c3d23448-b42a-11e4-8323-f3ebb3c138f1.png)
