### ISSUE TITLE
[ContentBundle] Exception when content_preview_url is not defined

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#425]
<a href="https://github.com/dantleech"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/530801?v=2" /></a>
By @dantleech *from* https://github.com/sulu-cmf/SuluContentBundle/issues/213

````
 [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                   
  You have requested a non-existent parameter "content_preview_url". Did you mean this: "content_preview_port"?
````

Should be required configuration or there should be a default. Same applies to other parameters.

**Comment by wachterjohannes** [comment]
this parameter will be removed with this PR https://github.com/sulu-cmf/sulu/pull/684
