### ISSUE TITLE
[ContentBundle] Add parent page to smart content data for template

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#432]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot *from* https://github.com/sulu-cmf/SuluContentBundle/issues/164

The parent or DataSource of the smart content should also be populated to the twig template, so that e.g. the name of the parent page can be used.

**Comment by danrot** [comment]
Should be fixed here: https://github.com/sulu-cmf/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Content/Types/SmartContent/SmartContent.php#L195

**Comment by wachterjohannes** [comment]
@danrot hmm i think this should include the page data of selected datasource ... but this is not used from everyone and if it is needed it can be loaded over `content_load(view.smart_content.dataspource)` so i think it is ok when it is closed!
