### ISSUE TITLE
[ContentBundle] StructureExtension documentation

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#437]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluContentBundle/issues/138

* https://github.com/sulu-cmf/sulu/pull/120
* https://github.com/sulu-cmf/SuluContentBundle/pull/137

**Comment by danrot** [comment]
@wachterjohannes Probably @dantleech will do that for you after the refactoring ;-)
