### ISSUE TITLE
[ContentBundle] Check Websocket online is available at login

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#438]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluContentBundle/issues/102

then use it in content-form or not (=.

**Comment by danrot** [comment]
@wachterjohannes I guess this is fixed by the refactored preview resp. websocket component? Please close if I am right.

**Comment by wachterjohannes** [comment]
yes not on login but only once (=
