### ISSUE TITLE
[LocationBundle] README file

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#443]
<a href="https://github.com/dantleech"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/530801?v=2" /></a>
By @dantleech *from* https://github.com/sulu-cmf/SuluLocationBundle/issues/6

**Comment by danrot** [comment]
Since the package merge not necessary anymore, and we should check all READMEs when doing the subtree split anyway. Closing...
