### ISSUE TITLE
[MediaBundle] media selection adding and removing elements

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#444]
<a href="https://github.com/michaelzangerle"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1465587?v=2" /></a>
By @michaelzangerle *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/109

I am not really sure how but sometimes when I add and remove elements (more than once) with the media selection I get following problem:
![bildschirmfoto 2014-10-28 um 17 29 57](https://cloud.githubusercontent.com/assets/1465587/4812371/0bb73fd0-5ec0-11e4-9c91-22908594349d.png)
The selection in the media-selection component does not match with the selection in the media- selection-list. In this case I have deselected an image but it is still in the list.

**Comment by danrot** [comment]
@michaelzangerle The handling of this content type should have improved by #806, so I close this issue. Please reopen it, if you run into it again.
