### ISSUE TITLE
[MediaBundle] Single and Multiple File Delete does not work

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#447]
<a href="https://github.com/pjeroen"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/513131?v=2" /></a>
By @pjeroen *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/73

Deleting a single file or mutliple files does not work. After confirming the warning dialog the files are still in the collection.

**Comment by danrot** [comment]
The UI could definitely be a bit better (showing some loader while files are deleted), but in general it works.
