### ISSUE TITLE
[MediaBundle] Media-Selection and functionality

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#459]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/14

* Media sorting
* Media selection style

now:
![image](https://cloud.githubusercontent.com/assets/1464615/3284750/25e1a0d4-f530-11e3-9be3-4da2600187d5.png)

should be:
![image](https://cloud.githubusercontent.com/assets/1464615/5113495/6e42b748-7030-11e4-8224-a84a6b17a6a7.png)

**Comment by wachterjohannes** [comment]
as if the design has changed a lot since i created this issue and the sorting is done by @danrot in https://github.com/sulu-cmf/sulu/pull/738 i close this issue
