### ISSUE TITLE
[TagBundle] Fix timing issue with husky auto complete list correctly

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#477]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot *from* https://github.com/sulu-cmf/SuluTagBundle/issues/7

At the moment a timeout is used, which is not a nice solution. See FIXME in 7b971306f4b12bed746035f761239c8fd03a8721

**Comment by danrot** [comment]
Just searched for setTimeout in the TagBundle, and I got no results, so I think this is solved.
