### ISSUE TITLE
[TranslateBundle] Import process timeout

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#480]
<a href="https://github.com/turbo-ele"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/5152633?v=2" /></a>
By @turbo-ele *from* https://github.com/sulu-cmf/SuluTranslateBundle/issues/52

on my machine (macbook pro mid 2009) i get the following error during composer update.
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "'/usr/local/php5-5.4.20-20130930-105609/bin/php' 'app/console' --ansi sulu:translate:import de" exceeded the timeout of 300 seconds.
```

repeating the command itself resolved the issue

**Comment by danrot** [comment]
ping @dantleech

**Comment by dantleech** [comment]
I may have improved it (I certainly made it look better). But it could still be much faster.

**Comment by danrot** [comment]
I think there is no timeout anymore, so I'll close this issue. Performance could be improved everywhere, not necessary to always have an issue for that :-)

**Comment by dantleech** [comment]
true .. although I think the performance could be *really* improved here :) But yeah thats close it.
