### ISSUE TITLE
[SearchBundle] Documents are not removed from index when they are unpublished

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#485]
<a href="https://github.com/dantleech"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/530801?v=2" /></a>
By @dantleech *from* https://github.com/sulu-cmf/SuluSearchBundle/issues/12

Task: Find a solution for that.

**Comment by danrot** [comment]
ping @dantleech

**Comment by dantleech** [comment]
Yep. Fixed.
