### ISSUE TITLE
[WebsiteBundle] Error page injects parameters that are available in other templates

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#487]
<a href="https://github.com/dantleech"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/530801?v=2" /></a>
By @dantleech *from* https://github.com/sulu-cmf/SuluWebsiteBundle/issues/67

These parameters are global and should not have to be injected independently in 2 different places. Would revert this change in some way: #66

**Comment by danrot** [comment]
@dantleech Can you further explain this issue? Or is the issue maybe even already solved?

**Comment by dantleech** [comment]
I think I am talking about things like the webspace and the locale. But lets close this as I don't really know.
The issue I was referring to was: https://github.com/sulu-cmf/SuluWebsiteBundle/pull/66/files
