### ISSUE TITLE
Version 0.10.2 property media_selection

### ISSUE THREAD

**Issue by Quehnie** [sulu-cmf/sulu#554]
If you assign more than 10 images in a media selection, they will be shown on the page, but if you want to delete or watch the assigned images in the media selection again you can't display more than 10 images.

![bildschirmfoto 2014-11-13 um 17 25 27](https://cloud.githubusercontent.com/assets/8446502/5031886/1cb61efe-6b5a-11e4-93a1-b2e89fc878d5.png)

**Comment by danrot** [comment]
Just tried, seem to be working now. I have assigned 12 images, and Sulu showed all of them to me. Can you try to reproduce it again, and close this issue, if you get the same result?
