### ISSUE TITLE
RepositoryException: Do not call login twice

### ISSUE THREAD

**Issue by turbo-ele** [sulu-cmf/sulu#561]
I get this on every restart:
RepositoryException: Do not call login twice. Rather instantiate a new Transport object to log in as different user or for a different workspace.
Clearing the cache helps.

**Comment by dantleech** [comment]
@turbo-ele do you still get this issue?

**Comment by turbo-ele** [comment]
i don't think so. if it reoccurs, i'll reopen this issue (if you'd like to close it)

**Comment by dantleech** [comment]
Cool
