### ISSUE TITLE
Language changer does not work in backoffice

### ISSUE THREAD

**Issue by dantleech** [sulu-cmf/sulu#574]
Changing the language in the back office does not work with Chrome

It sends a request to:

````
http://sulu.lo/admin/api/users/159
````

and there is a 400 error:

````
HTTP/1.1 400 Invalid header received from client
Proxy-Agent: Privoxy 3.0.21
Content-Type: text/plain
Connection: close

````

Note also that this does not seem to work with the functional test (the language is not changed although the page is reloaded and the option is changed).

**Comment by dantleech** [comment]
Note that the behat feature (`AdminBundle/Features/change_language`) has been left incomplete because this would otherwise cause it to fail. It should be completed when this issue is fixed.

**Comment by danrot** [comment]
Just tested, it is working again.
