### ISSUE TITLE
Cache is not cleared when a xml definition is changed

### ISSUE THREAD

**Issue by danrot** [sulu-cmf/sulu#62]
When e.g. a workspace definition changes, there is no invalidating of the cache, so it has to be deleted manually.

**Comment by dantleech** [comment]
@danrot is this still an issue?

**Comment by danrot** [comment]
I am not sure, would have to test. Probably it is, because AFAIK nobody worked on it.

**Comment by dantleech** [comment]
Shall we assign to you?

**Comment by dantleech** [comment]
Modifying the webspace definition has immediate effect in the `dev` env. Closing.
