### ISSUE TITLE
Preview Ajax Fallback on Windows Very Slow

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#621]
On Windows (tested in Firefox) the fallback to ajax need 10-15 seconds before loading the preview.
Maybe we can find a fast way to check if Server Socket is running.

After the detection function in preview js we should do an ajax to a new controller Action. PreviewController:checkSocketRunning for example. And check over PHP if connection is possible to socket with faster timeout. So we don't need to wait for a socket.error. If the response is true use socket else use ajax.

**Comment by wachterjohannes** [comment]
now we only check websocket once ... this should fasten it very well (= if this is not enough websocket can be set to false in config if it is not started!
