### ISSUE TITLE
Add getPropertyContentValue function to Structure

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#657]
We should add the ContentTypeManager to Structure to give the developer an easy function to get the correct value of an content type.

**Comment by danrot** [comment]
I don't know if it is a good idea to inject a service to the structure, since it is just a data container till now.

**Comment by wachterjohannes** [comment]
i agree with @danrot additionally all of this will change with the work on the content mapper! For my feel we should close this issue!
