### ISSUE TITLE
Command for creating an user fails if there is no role

### ISSUE THREAD

**Issue by danrot** [sulu-cmf/sulu#683]
If you execute the following command:

```
app/console sulu:security:user:create
```

When you should enter the choice for the role the following error appears multiple times:

```
Warning: max(): Array must contain at least one element in /Users/daniel/Development/massiveart/sulu-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/QuestionHelper.php line 116
```

**Comment by dantleech** [comment]
I thought there was an issue for this already but I can't find it.

**Comment by danrot** [comment]
I guess you are talking about #656 , but that's a different issue. Was probably introduced when fixing that.
