### ISSUE TITLE
Block default login on production environment

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#690]
I would prefer to block the default login "admin" with password "admin" on production. 
As a human security feature this login should be blocked when a website is going in production.

So we have no insecure working default logins in production.

**Comment by danrot** [comment]
Nobody forces you to create this user, so I would just suggest to not create it. Is not really an issue to me.

**Comment by wachterjohannes** [comment]
same for me ... but we should make it decidable in the `sulu:build` command!

**Comment by alexander-schranz** [comment]
and we just dont define a default password and he need to enter it in the sulu:build command.

**Comment by danrot** [comment]
There is already the `prod`-target, which does not automatically create a user. Just use this one and the `sulu:security:user:create` afterwards. The build command is not intended to be used with any kind of interaction, so this is not an issue for me.
