### ISSUE TITLE
Add dependency injection to client/website/bundle

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#722]

**Comment by dantleech** [comment]
Can explain some more?

**Comment by alexander-schranz** [comment]
in mostly all projects we need to define own services (mostly a twig extension) or load data(mail addresses, ...) from the config so it would be good that the DependencyInjection files (ClientWebsiteExtension, DependencyInjection) to set the config or load services.xml is in the default sulu installation. see sulu-cmf/sulu-standard#395

**Comment by dantleech** [comment]
Makes sense. Although I wonder if ultimately we could have a command to generate stuff like this interactively (.. well there actually is one but I am not sure it works very well). But that would be something to discuss later.
