### ISSUE TITLE
Version 13.2: Test Error 404 Page

### ISSUE THREAD

**Issue by Quehnie** [sulu-cmf/sulu#723]
Is there a way to see my Error 404 Page?
I get this page, but i want to see my error404 view.

![bildschirmfoto 2015-01-16 um 14 35 39](https://cloud.githubusercontent.com/assets/8446502/5776842/43e94b80-9d8d-11e4-8772-717bffc589c9.png)
![bildschirmfoto 2015-01-16 um 14 36 22](https://cloud.githubusercontent.com/assets/8446502/5776843/47409d42-9d8d-11e4-8fd6-3df3009dd3ba.jpg)

**Comment by dantleech** [comment]
You need to run the website in PROD mode.

One easy way to do this is to launch a webserver just for the website:

````
$env APP_ENV=prod php app/console server:run sulu.lo:8002 --router=app/config/router_website.php
````

Then access it on:

````
sulu.lo:8002
````

**Comment by dantleech** [comment]
Can you create an issue on https://github.com/sulu-cmf/sulu-docs ?

**Comment by alexander-schranz** [comment]
@dantleech there should be another way for people who only develop a theme without ssh access to the server to see there error 404 page

**Comment by dantleech** [comment]
I agree .. but how can you develop a theme without access to the server? /cc @chirimoya

**Comment by dantleech** [comment]
We should also find a way that people can develop locally with large client websites, developing on `burns.at` isn't very scalable if I understand correctly.

**Comment by dantleech** [comment]
As of Symfony 2.6 this will be possible: http://symfony.com/blog/new-in-symfony-2-6-error-page-previews

We are hopefully going to upgrade this week,

**Comment by danrot** [comment]
We upgraded to Symfony 2.6, so you will have the possibility to display these error pages.
