### ISSUE TITLE
Add dummy analyticsKey to preview

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#755]
Currently it will error because request.analyticsKey don't exists in preview:

https://github.com/sulu-cmf/docs/blob/9bb8d1661e2045cde3cd3fda33e63fe90dd6a624/developer-documentation/300-webspaces/templates.md

+ We should also add the thrown exception in the preview into the log as error currently its catch but you dont get the error in the log when you have a custom error site.

**Comment by wachterjohannes** [comment]
@alexander-schranz which key should i use for preview?

**Comment by alexander-schranz** [comment]
@wachterjohannes I think we should add something like UA-SULU-PREVIEW-KEY

**Comment by wachterjohannes** [comment]
hard coded or configuration?

**Comment by alexander-schranz** [comment]
we should make it be overwriteable in the config.yml but default i would set.

**Comment by wachterjohannes** [comment]
ok!
