### ISSUE TITLE
Strange characters appearing in administration

### ISSUE THREAD

**Issue by matejvelikonja** [sulu-cmf/sulu#766]
Occasionally it happens that administration breaks down and starts showing weird characters instead of icons. Changing language in administration helps, and the icons are again shown properly. The bug was found on latest Chrome on OsX.

![screen shot 2015-01-29 at 15 48 50](https://cloud.githubusercontent.com/assets/1881087/5959446/a8e02cf2-a7ce-11e4-9b92-f38529b449d0.png)

**Comment by danrot** [comment]
The icons are from a font, can you check if this font is correctly loaded in the network tab of the developer tools?

**Comment by alexander-schranz** [comment]
i had this also once deleting the client cache and relogin did fix the problem for me.

**Comment by matejvelikonja** [comment]
thx for the tips. I will check this stuff when/if the errors occurs again.

**Comment by danrot** [comment]
@matejvelikonja Can we consider this fixed with the tips?
