### ISSUE TITLE
Delete clean from Gruntfiles build command

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#769]
Mostly we work in development with `assets:install --symlink --relative` if you run the GruntFiles of the Sulu bundles (grunt build) it will not work the grunt clean process deletes the original files because of the symlink.

**Comment by wachterjohannes** [comment]
@danrot how should we handle this in the future? we should change our development to symlinking assets with `app/console assets:install --symlink`. @alexander-schranz works this for you? /cc @chirimoya @dantleech

**Comment by danrot** [comment]
Wasn't symlinking an issue with requirejs?

**Comment by wachterjohannes** [comment]
but it seems to work upstairs @chirimoya said its ok now ... but i thought that too!

**Comment by alexander-schranz** [comment]
@wachterjohannes  `--symlink` or `--symlink --relative` is the same but `grunt build` calls `clean:public` and this deletes the original files then. We should delete `clean:public` from `grunt build`. We can add a additional command `grunt clean-build` for this who are not working with symlinks.

**Comment by danrot** [comment]
Maybe it's only not working on macs?

**Comment by danrot** [comment]
Just tested, it works. And we actually SHOULD remove it, since it looks like symlinking is the new default in Symfony 2.6

**Comment by wachterjohannes** [comment]
perhaps we forgotten this --relative flag!

**Comment by danrot** [comment]
We just found out that this can be configured via the following line: https://github.com/sulu-cmf/sulu-standard/blob/develop/composer.json#L68

How should we handle this now? Does everybody have to work with symlinks? Or should we remove this line? Makes it less comfortable to use `app/console assets:install`, because you have to think about the flags you have to pass.

/cc @chirimoya @notsure

**Comment by notsure** [comment]
After talking to @danrot I agree with @alexander-schranz 

We should remove the grunt-clean task. As @danrot told me (and I could already verify it) symfony is making symlinks for all its bundles. so if we are compiling our static files to a "dist" directory in the public folder (as we already do) we don't need the "grunt-clean" and the "publish" task anymore. 

plus we do no longer need to copy images or fonts or whatever into dist folders.

**Comment by notsure** [comment]
currently fixing it

**Comment by danrot** [comment]
fixed by #801

**Comment by notsure** [comment]
https://github.com/sulu-cmf/sulu/pull/801
