### ISSUE TITLE
[MediaBundle] Enable sorting of media

### ISSUE THREAD

**Issue by dantleech** [sulu-cmf/sulu#772]
The user should be able to sort the medias in the selector.

(moved from sulu-standard https://github.com/sulu-cmf/sulu-standard/issues/403)

/cc @tomsvogel

**Comment by dantleech** [comment]
I think @danrot is doing this, see also https://github.com/sulu-cmf/sulu/issues/459

**Comment by wachterjohannes** [comment]
done by @danrot in https://github.com/sulu-cmf/sulu/pull/738 . i have created a new issue for snippet and internal link selection https://github.com/sulu-cmf/sulu/issues/780
