### ISSUE TITLE
Problem uploading assets (file size > 2mb)

### ISSUE THREAD

**Issue by crash0verride** [sulu-cmf/sulu#803]
If I try to upload an asset with file size bigger than 2mb, the upload starts till the blue status bar is filled, but stops there without refreshing or showing the new asset. A manual refresh doesn't fix the problem.

Network monitor shows the following status: Status-Code: 	HTTP/1.1 413 Request Entity Too Large

**Comment by alexander-schranz** [comment]
should be a server setting will have a look at it.

**Comment by alexander-schranz** [comment]
seems that the nginx default setting for `client_max_body_size` is <2mb.
@crash0verride now the file upload should work
