### ISSUE TITLE
Categories are not sortable by name

### ISSUE THREAD

**Issue by danrot** [sulu-cmf/sulu#824]
If you try to sort the categories by name in the following list, they are just disappearing.
![image](https://cloud.githubusercontent.com/assets/405874/6165493/b3e15a1a-b2a8-11e4-9354-c3604de20dd8.png)
The following error message is shown in the console:
```
Uncaught TypeError: Cannot set property 'childrenLoaded' of undefined
```

**Comment by michaelzangerle** [comment]
@danrot should be fixed with the changes I made in husky

**Comment by danrot** [comment]
@michaelzangerle Can you link the PR here?

**Comment by michaelzangerle** [comment]
https://github.com/massiveart/husky/pull/451
