### ISSUE TITLE
Media DisplayOption not implemented for website?

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#827]
How to get the selected media display option in twig?
(https://github.com/sulu-cmf/docs/blob/master/developer-documentation/500-assets/media-selection.md)

**Comment by danrot** [comment]
I guess via the `view`-variable.

**Comment by alexander-schranz** [comment]
@danrot did add it to the docs: https://github.com/sulu-cmf/docs/pull/13/files
