### ISSUE TITLE
Remove var_dump

### ISSUE THREAD

**Issue by wachterjohannes** [sulu-cmf/sulu#834]
see https://scrutinizer-ci.com/g/sulu-cmf/sulu/issues/develop/files/src/Sulu/Bundle/TestBundle/Behat/BaseContext.php#inspectioncomment-558141204

**Comment by danrot** [comment]
@dantleech Can't you fix this very fast?

**Comment by dantleech** [comment]
Removed and pushed to develop.

**Comment by danrot** [comment]
@dantleech Actually we never push to develop without a review, doesn't matter how small the change is ;-)
