### ISSUE TITLE
Server Error 500 saving changes when translating a page

### ISSUE THREAD

**Issue by crash0verride** [sulu-cmf/sulu#903]
When I try to save a new translation of a page, Sulu returns the server error 500, changes are sometimes dismissed. 
![sulu-error-500](https://cloud.githubusercontent.com/assets/3469973/6522770/37e6b0e8-c3e9-11e4-81db-617209bdd1e4.jpg)

**Comment by berndhep** [comment]
Related to #906

**Comment by chirimoya** [comment]
@crash0verride it was a server issue, should be fixed now. But please keep an eye on. thx.
