### ISSUE TITLE
Error on Upgrade Scripts 0.15 and 0.16

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#906]
get the following error when updating from 0.14.0 to 0.16.1in the both update scripts (0.15 internal links, 0.16 time) 
(staging environment)

```
[PHPCR\RepositoryException]
  Not a valid json object:
  Request: POST http://localhost:8080/jackrabbit/server/sulu_staging/jcr:root/.0.json
  Response:
```

**Comment by alexander-schranz** [comment]
did talk with @c00n84 about this error.
Its a bug on the server with `CURL` version `7.35` 
updating `CURL` to `7.36.0` did fix the bug.

maybe add this specific CURL version as conflict to composer.json? @danrot 
``` json
"conflict": {
    "lib-curl": "7.35"
},
```

**Comment by chirimoya** [comment]
@alexander-schranz Jackalope has this conflict already:
https://github.com/jackalope/jackalope-jackrabbit/issues/89 
https://github.com/jackalope/jackalope-jackrabbit/pull/95/files

Reading the warnings while installation would help ;-)
